# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-nuke" do
  name "kubectl-nuke"
  desc "kubectl plugin to forcefully delete Kubernetes resources"
  homepage "https://github.com/codesenju/kubectl-nuke-go"
  version "0.9.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-nuke"

  on_macos do
    on_intel do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-darwin-amd64.tar.gz"
      sha256 "e8bbd71d2a17a33ffa63e89b577c4855e2481b52676ebc890dfea860c0380142"
    end
    on_arm do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-darwin-arm64.tar.gz"
      sha256 "b69d10d86f3bff31be4548c61215a8fded98208042c53c93e3651a0e72a85fc1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-linux-amd64.tar.gz"
      sha256 "618aee76b64f25e8874c1b92b7c3736243d6ad923a8998643fa788e2ec535acd"
    end
    on_arm do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-linux-arm64.tar.gz"
      sha256 "f4381ed1cd6e81b8b8f59ef423ceb24b30ba570434b4be39239d6232916dfea6"
    end
  end

  # No zap stanza required
end
