# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-nuke" do
  version "0.9.7"

  on_macos do
    on_intel do
      sha256 "708cb62b31e3e9889547c351958d0777b80528e2d68c813b97ad84f61d7fb473"
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "fbfad6fb38c9119aade99ab5083cad6be6b0553620dd4f98c60e3146cb0d6d8a"
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65ccb7330a85060f284feb28dd3658ebfe5b0a6abbf27accbdbc24089dea6f06"
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "bd2066636ff16fac572b161f6048805e2f596b6af7c5dfa00cdaaa911cf32ded"
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v#{version}/kubectl-nuke-go-linux-arm64.tar.gz"
    end
  end

  name "kubectl-nuke"
  desc "kubectl plugin to forcefully delete Kubernetes resources"
  homepage "https://github.com/codesenju/kubectl-nuke-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-nuke"

  # No zap stanza required

end
