# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-nuke" do
  desc "kubectl plugin to forcefully delete Kubernetes resources"
  homepage "https://github.com/codesenju/kubectl-nuke-go"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-nuke"

  on_macos do
    on_intel do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v0.7.0/kubectl-nuke-go-darwin-amd64.tar.gz"
      sha256 "181ea68b1fdf4e3da22d3fad50989933c164378f93da03753e6d8570f0c5d00b"
    end
    on_arm do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v0.7.0/kubectl-nuke-go-darwin-arm64.tar.gz"
      sha256 "cec9dd4e3c90b8e2ca74c1a8540932888ae05a481ff1aa607dc275c056e91f43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v0.7.0/kubectl-nuke-go-linux-amd64.tar.gz"
      sha256 "3e2d3d4db2c4adb6a8f13a839d7d8e29173ba6331bdf73a3972a336ebb361c47"
    end
    on_arm do
      url "https://github.com/codesenju/kubectl-nuke-go/releases/download/v0.7.0/kubectl-nuke-go-linux-arm64.tar.gz"
      sha256 "0448eb0388989b7106727e3a025879c6b931958d2978b9cb9b0dc2f5a306a574"
    end
  end

  # No zap stanza required
end
